application/views/client/gifts/views.py
#!/usr/bin/env python

"""Define routes for CRUD operations on gifts."""

from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from application.models import (Base,
                    User,
                    Gift,
                    Claim,
                    Category)

from flask import (request,
                   redirect,
                   url_for,
                   render_template,
                   flash,
                   session,
                   Blueprint,
                   Markup)

# For making decorators
from functools import wraps

from datetime import datetime, timedelta

# Bind database
engine = create_engine('sqlite:///giftr.db')
Base.metadata.bind = engine
DBSession = sessionmaker(bind=engine)
c = DBSession()

gifts_blueprint = Blueprint('gifts', __name__, template_folder='templates')


# DECORATORS
def login_required(f):
    """Redirect to login page if the user is not logged in (decorator)."""
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if 'username' not in session:
            flash('You need to be logged in to see that page.')
            return redirect(url_for('login.show'))
        return f(*args, **kwargs)
    return decorated_function


def include_gift(f):
    """Take a g_id kwarg and return a gift object (decorator)."""
    @wraps(f)
    def decorated_function(*args, **kwargs):
        g_id = kwargs['g_id']
        gift = c.query(Gift).filter_by(id=g_id).one_or_none()
        if not gift:
            flash('There\'s no gift here.')
            return redirect(url_for('gifts.get'))
        # pass along the gift object to the next function
        kwargs['gift'] = gift
        return f(*args, **kwargs)
    return decorated_function


def include_categories(f):
    """Return an object with all categories (decorator)."""
    @wraps(f)
    def decorated_function(*args, **kwargs):
        categories = c.query(Category).all()
        # pass along the categories object to the next function
        kwargs['categories'] = categories
        return f(*args, **kwargs)
    return decorated_function


def creator_required(f):
    """Take a gift kwarg and redirect to gifts.getbyid if user is not that gift's creator (decorator)."""  # noqa
    @wraps(f)
    def decorated_function(*args, **kwargs):
        gift = kwargs['gift']

        if gift.creator_id != session.get('user_id'):
            flash('You have to be the creator of that gift to see that page.')
            return redirect(url_for('gifts.get_byid',
                                    g_id=gift.id))
        return f(*args, **kwargs)
    return decorated_function


def open_required(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        gift = kwargs['gift']

        if not gift.open:
            flash('You cannot do this anymore. The gift has been promised.')
            return redirect(url_for('gifts.get'))
        return f(*args, **kwargs)
    return decorated_function


# ROUTES

@gifts_blueprint.route('/', methods=['GET'])
@gifts_blueprint.route('/gifts', methods=['GET'])
@include_categories
def get(categories):
    """Render all gifts or gifts of category id "cat" if query.

    Argument:
    categories (object): generally passed through the
                         @include_categories decorator,
                         contains all categories in the database.
    """
    req_cat = request.args.get('cat')

    # If there is a valid int as query string,
    # filter the gifts by category
    try:
        req_cat = int(req_cat)
        if req_cat > 0 and req_cat <= len(categories):
            gifts = c.query(Gift).filter_by(category_id=req_cat).filter(Gift.expires_at > datetime.now()).order_by(Gift.expires_at.desc()).all()  # noqa
            req_cat = c.query(Category).filter_by(id=req_cat).first()

            return render_template('gifts.html',
                                   gifts=gifts,
                                   categories=categories,
                                   req_cat=req_cat,
                                   page="gifts")
    except:
        pass

    gifts = c.query(Gift).filter(Gift.expires_at > datetime.now()).order_by(Gift.expires_at.desc()).all()

    return render_template('gifts.html',
                           categories=categories,
                           gifts=gifts,
                           page="gifts")


@gifts_blueprint.route('/gifts/<int:g_id>', methods=['GET'])
@include_gift
@include_categories
def get_byid(g_id, gift, categories):
    """Render a gift of id g_id.

    Login required.

    Arguments:
    g_id (int): the id of the desired gift.
    gift (object): generally passed through the @include_gift decorator,
                   contains a gift object of id g_id.
    categories (object): generally passed through the
                         @include_categories decorator,
                         contains all categories in the database.
    """
    # If user is gift's creator and that gift expired, flash them
    if session.get('username'):
        if gift.creator_id == session.get('user_id'):
            if gift.expires_at < datetime.now():
                msg = """<form method="POST" action="%s">
                            Your gift expired.
                            <input type="submit" class="btn btn-success ml-4" value="Bring it back to life for 5 days"></input>
                         </form>""" % url_for('gifts.extend', g_id=g_id)
                flash(Markup(msg))

    return render_template('gift.html',
                           gift=gift,
                           categories=categories,
                           page="gift")


@gifts_blueprint.route('/gifts/user/<int:u_id>', methods=['GET'])
@include_categories
def get_byuserid(u_id, categories):
    """Render all gifts created by a user of id u_id.

    Arguments:
    u_id (int): the id of the desired user.
    categories (object): generally passed through the
                         @include_categories decorator,
                         contains all categories in the database.
    """
    gifts = c.query(Gift).filter_by(creator_id=u_id).order_by(Gift.created_at.desc()).all()  # noqa
    user = c.query(User).filter_by(id=u_id).first()

    return render_template('gifts.html',
                           gifts=gifts,
                           categories=categories,
                           user=user,
                           page="usergifts")


@gifts_blueprint.route('/gifts/add', methods=['GET'])
@login_required
@include_categories
def add_get(categories):
    """Render form to add a gift.

    Login required.

    Argument:
    categories (object): generally passed through the
                         @include_categories decorator,
                         contains all categories in the database.
    """
    return render_template('add_gift.html',
                           categories=categories)


@gifts_blueprint.route('/gifts/add', methods=['POST'])
@login_required
def add_post():
    """Add a gift to the database with POST.

    Login required.
    """
    gift = Gift(name=request.form.get('name'),
                picture=request.form.get('picture'),
                description=request.form.get('description'),
                category_id=request.form.get('category'),
                creator_id=session.get('user_id'))
    c.add(gift)
    c.commit()

    flash("Thanks for your generosity! %s was successfully added." % gift.name)

    return redirect(url_for('gifts.get_byid',
                            g_id=gift.id))


@gifts_blueprint.route('/gifts/<int:g_id>/edit', methods=['GET'])
@login_required
@include_gift
@creator_required
@open_required
@include_categories
def edit_get(g_id, gift, categories):
    """Render an edit form for a gift of id g_id.

    Login required.
    One has to be the creator of the gift to access this.

    Argument:
    g_id (int): the id of the desired gift.
    gift (object): generally passed through the @include_gift decorator,
                   contains a gift object of id g_id.
    categories (object): generally passed through the
                         @include_categories decorator,
                         contains all categories in the database.
    """
    return render_template('edit_gift.html',
                           gift=gift,
                           categories=categories)


@gifts_blueprint.route('/gifts/<int:g_id>/edit', methods=['POST'])
@login_required
@include_gift
@open_required
@creator_required
def edit_post(g_id, gift):
    """Edit a gift of id g_id with POST.

    Login required.
    One has to be the creator of the gift to access this.

    Arguments:
    g_id (int): the id of the desired gift.
    gift (object): generally passed through the @include_gift decorator,
                   contains a gift object of id g_id.
    """
    gift.name = request.form.get('name')
    gift.picture = request.form.get('picture')
    gift.description = request.form.get('description')
    gift.category_id = request.form.get('category')

    c.add(gift)
    c.commit()

    flash("%s was successfully edited." % gift.name)

    return redirect(url_for('gifts.get_byid',
                            g_id=gift.id))


@gifts_blueprint.route('/gifts/<int:g_id>/delete', methods=['GET'])
@login_required
@include_gift
@open_required
@creator_required
def delete_get(g_id, gift):
    """Render a delete form for a gift of id g_id.

    Login required.
    One has to be the creator of the gift to access this.

    Arguments:
    g_id (int): the id of the desired gift.
    gift (object): generally passed through the @include_gift decorator,
                   contains a gift object of id g_id.
    """
    return render_template('delete_gift.html',
                           gift=gift)


@gifts_blueprint.route('/gifts/<int:g_id>/delete', methods=['POST'])
@login_required
@include_gift
@open_required
@creator_required
def delete_post(g_id, gift):
    """Delete a gift of id g_id with POST.

application/views/client/gifts/templates/add_gift.html
{% extends "index.html" %}

{% block header %}
<header class="jumbotron">
	<h1 class="display-4">Give something</h1>
</header>
{% endblock %}

{% block nav %}
<ol class="breadcrumb ml-auto mb-0" style="padding:.5rem 1rem;">
    <li class="breadcrumb-item"><a href="{{ url_for('gifts.get') }}">Gifts</a></li>
    <li class="breadcrumb-item active" aria-current="page">Add</li>
</ol>
{% endblock %}

{% block body %}
<form method='POST' action="{{ url_for('gifts.add_post') }}">
	<input name="_csrf_token" type="hidden" value="{{ csrf_token() }}">

    <div class="form-group">
		<label for="name">Name</label>
    	<input id="name" class="form-control" type='text' name='name' placeholder='Name'>
    </div>

    <div class="form-group">
    	<label for="picture">Picture URL</label>
    	<input id="picture" class="form-control" type='text' name='picture' placeholder='Picture URL'>
    </div>

    <div class="form-group">
    	<label for="description">Description</label>
    	<textarea id="description" class="form-control" name='description' placeholder='Description'></textarea>
    </div>

    <div class="form-group">
    	<label for="category">Category</label>
    	<select id="category" class="form-control" name="category">
    		{% for category in categories %}
    		<option value="{{ category.id }}">{{ category.name }}</option>
    		{% endfor %}
    	</select>
    </div>

    <button class="btn btn-outline-success" type="submit">Gift</button>
</form>
{% endblock %}

application/views/client/gifts/templates/delete_gift.html
{% extends 'index.html' %}

{% block header %}
{% if gift.category.picture %}
<header class="jumbotron" style="background: url('{{ gift.category.picture }}') no-repeat; background-size: cover;">
{% else %}
<header class="jumbotron">
{% endif %}
	<h1 class="display-4">Delete {{ gift.name | truncate(50) }}?</h1>
</header>
{% endblock %}

{% block nav %}
<ol class="breadcrumb ml-auto mb-0" style="padding:.5rem 1rem;">
	<li class="breadcrumb-item"><a href="{{ url_for('gifts.get') }}">Gifts</a></li>
    <li class="breadcrumb-item"><a href="{{ url_for('gifts.get', cat=gift.category.id) }}">{{ gift.category.name }}</a></li>
    <li class="breadcrumb-item"><a href="{{ url_for('gifts.get_byid', g_id=gift.id) }}">{{ gift.name | truncate(25) }}</a></li>
    <li class="breadcrumb-item active" aria-current="page">Delete</li>
</ol>
{% endblock %}

{% block body %}
<form method="POST" action="{{ url_for('gifts.delete_post', g_id=gift.id) }}" class="text-center">
	<input name="_csrf_token" type="hidden" value="{{ csrf_token() }}">

	<button class="btn btn-danger btn-lg" type="submit">Confirm</button>
</form>
{% endblock %}

application/views/client/gifts/templates/edit_gift.html
{% extends 'index.html' %}

{% block header %}
{% if gift.category.picture %}
<header class="jumbotron" style="background: url('{{ gift.category.picture }}') no-repeat; background-size: cover;">
{% else %}
<header class="jumbotron">
{% endif %}
	<h1 class="display-4">Edit {{ gift.name | truncate(50) }}</h1>
</header>
{% endblock %}

{% block nav %}
<ol class="breadcrumb ml-auto mb-0" style="padding:.5rem 1rem;">
	<li class="breadcrumb-item"><a href="{{ url_for('gifts.get') }}">Gifts</a></li>
    <li class="breadcrumb-item"><a href="{{ url_for('gifts.get', cat=gift.category.id) }}">{{ gift.category.name }}</a></li>
    <li class="breadcrumb-item"><a href="{{ url_for('gifts.get_byid', g_id=gift.id) }}">{{ gift.name | truncate(25) }}</a></li>
    <li class="breadcrumb-item active" aria-current="page">Edit</li>
</ol>
{% endblock %}

{% block body %}
<form method="POST" action="{{ url_for('gifts.edit_post', g_id=gift.id) }}">
    <input name="_csrf_token" type="hidden" value="{{ csrf_token() }}">

	<div class="form-group">
		<label for="name">Name</label>
    	<input id="name" class="form-control" type='text' name='name' placeholder='Name' value='{{ gift.name }}'>
    </div>

    <div class="form-group">
    	<label for="picture">Picture URL</label>
    	<input id="picture" class="form-control" type='text' name='picture' placeholder='Picture URL' value='{{ gift.picture }}'>
    </div>

    <div class="form-group">
    	<label for="description">Description</label>
    	<textarea id="description" class="form-control" name='description' placeholder='Description'>{{ gift.description }}</textarea>
    </div>

    <div class="form-group">
    	<label for="category">Category</label>
    	<select id="category" class="form-control" name="category">
    		{% for category in categories %}
    		{% if category.id == gift.category_id %}
    		<option value="{{ category.id }}" selected>{{ category.name }}</option>
    		{% else %}
    		<option value="{{ category.id }}">{{ category.name }}</option>
    		{% endif %}
    		{% endfor %}
    	</select>
    </div>

    <button class="btn btn-outline-success" type="submit">Edit</button>
</form>
{% endblock %}

application/views/client/gifts/templates/gift.html
{% extends "index.html" %}

{% block header %}
{% if gift.category.picture %}
<header class="jumbotron" style="background: url('{{ gift.category.picture }}') no-repeat; background-size: cover;">
{% else %}
<header class="jumbotron">
{% endif %}
	<h1 class="display-4">{{ gift.name | truncate(50) }}</h1>
	<p class="lead">{{ gift.category.name }}</p>
</header>
{% endblock %}

{% block nav %}
<ol class="breadcrumb ml-auto mb-0" style="padding:.5rem 1rem;">
	<li class="breadcrumb-item"><a href="{{ url_for('gifts.get') }}">Gifts</a></li>
    <li class="breadcrumb-item"><a href="{{ url_for('gifts.get', cat=gift.category.id) }}">{{ gift.category.name }}</a></li>
    <li class="breadcrumb-item active" aria-current="page">{{ gift.name | truncate(25) }}</li>
</ol>
{% endblock %}

{% block body %}

{% include 'gift_card.html' %}

{% endblock %}

application/views/client/gifts/templates/gift_card.html
<div class="card card-block mx-auto">
	{% if gift.picture %}
	<div class="card-img img-link pop">
		<img class="card-img-top img-fluid" src="{{ gift.picture }}">
	</div>
	{% endif %}
	{% if (not session.username or gift.creator_id != session.user_id) and gift.open %}
	<a href="{{ url_for('claims.add_get', g_id=gift.id) }}" class="btn btn-success">Claim</a>
	{% endif %}
	<div class="card-body">
		<a href="{{ url_for('gifts.get_byid', g_id=gift.id) }}">
			<h5 class="card-title mb-0">{{ gift.name }}</h5>
		</a>
		<span class="badge badge-secondary mb-3">{{ gift.category.name }}</span>
		{% if not gift.open %}
		<span class="badge badge-success">Promised</span>
		{% endif %}
		<small class="float-right text-muted">Offered by <a href="{{ url_for('users.get_byid', u_id=gift.creator_id) }}">{{ gift.creator.name }}</a></small>
		<p class="card-text mb-2">{{ gift.description }}</p>
		<p class="card-text">
			<small class="text-muted">
				Expires on {{ gift.expires_at.strftime('%d %b %Y at %H:%M') }}<br>
				{% if gift.updated_at %}
				Last updated on {{ gift.updated_at.strftime('%d %b %Y at %H:%M') }}
				{% else %}
				Created on {{ gift.created_at.strftime('%d %b %Y at %H:%M') }}
				{% endif %}
			</small>
		</p>
		<div class="links text-center">
			{% if page == "gifts" %}
			<a href="{{ url_for('gifts.get_byid', g_id=gift.id) }}" class="btn btn-info mb-2">View</a>
			{% elif page == "gift" %}
			<a href="{{ url_for('claims.get', g_id=gift.id) }}" class="btn btn-outline-info mb-2">Claims</a>
			{% endif %}
			{% if session.username and gift.creator_id == session.user_id and gift.open %}
			<a href="{{ url_for('gifts.edit_get', g_id=gift.id) }}" class="btn btn-outline-warning mb-2">Edit</a>
			<a href="{{ url_for('gifts.delete_get', g_id=gift.id) }}" class="btn btn-outline-danger mb-2">Delete</a>
			{% endif %}
		</div>
	</div>
</div>

<div class="modal fade" id="imagemodal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">              
      <div class="modal-body">
      	<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <img src="" class="imagepreview" style="width: 100%;" >
      </div>
    </div>
  </div>
</div>

<script>
	$(function() {
		$('.pop').on('click', function() {
			$('.imagepreview').attr('src', $(this).find('img').attr('src'));
			$('#imagemodal').modal('show');   
		});		
	});
</script>

application/views/client/gifts/templates/gifts.html
{% extends "index.html" %}

{% block nav %}
<form class="form-inline justify-content-center ml-auto" method="GET" action="{{ url_for('gifts.get') }}">
	<select class="form-control" name="cat" onchange='this.form.submit();'>
		<option value="">All</option>
		{% for category in categories %}
		{% if req_cat and req_cat.id == category.id %}
		<option value="{{ category.id }}" selected>{{ category.name }}</option>
		{% else %}
		<option value="{{ category.id }}">{{ category.name }}</option>
		{% endif %}
		{% endfor %}
	</select>
</form>
{% endblock %}

{% block header %}
{% if req_cat and req_cat.picture %}
<header class="jumbotron" style="background: url('{{ req_cat.picture }}') no-repeat; background-size: cover;">
{% else %}
<header class="jumbotron">
{% endif %}
	{% if req_cat %}
	<h1 class="display-4">{{ req_cat.name }}</h1>
	{% elif user %}
	<h1 class="display-4">Gifts by {{ user.name }}</h1>
	{% else %}
	<h1 class="display-4">All the gifts</h1>
	{% endif %}
</header>
{% endblock %}

{% block body %}
<div class="gifts">
	<div class="grid">
		{% for gift in gifts %}
		<div class="grid-item">
		{% include 'gift_card.html' %}
		</div>
		{% endfor %}
	</div>
</div>
{% endblock %}