application/views/client/categories/views.py
#!/usr/bin/env python

"""Define routes for CRUD operations on categories."""

from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from application.models import (Base,
                    Category)

from flask import (request,
                   redirect,
                   url_for,
                   render_template,
                   flash,
                   session,
                   Blueprint)

# For making decorators
from functools import wraps

# Bind database
engine = create_engine('sqlite:///giftr.db')
Base.metadata.bind = engine
DBSession = sessionmaker(bind=engine)
c = DBSession()

categories_blueprint = Blueprint('categories', __name__, template_folder='templates')  # noqa


# DECORATORS
def login_required(f):
    """Redirect to login page if the user is not logged in (decorator)."""
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if 'username' not in session:
            flash('You need to be logged in to see that page.')
            return redirect(url_for('login.show'))
        return f(*args, **kwargs)
    return decorated_function


# ROUTES

@categories_blueprint.route('/categories', methods=['GET'])
def get():
    """Render all categories in the database."""
    categories = c.query(Category).all()

    return render_template('categories.html',
                           categories=categories)


@categories_blueprint.route('/categories/<int:cat_id>', methods=['GET'])
def get_byid(cat_id):
    """Render a category of id cat_id.

    Argument:
    cat_id (int): the id of the desired category.
    """
    category = c.query(Category).filter_by(id=cat_id).first()

    return render_template('category.html',
                           category=category)


@categories_blueprint.route('/categories/add', methods=['GET'])
@login_required
def add_get():
    """Render form to add a category.

    Login required.
    """
    return render_template('add_category.html')


@categories_blueprint.route('/categories/add', methods=['POST'])
@login_required
def add_post():
    """Add a category to the database with POST.

    Login required.
    """
    category = Category(name=request.form.get('name'),
                        picture=request.form.get('picture'),
                        description=request.form.get('description'))

    c.add(category)
    c.commit()

    flash("The category \"%s\" was successfully added." % category.name)

    return redirect(url_for('categories.get_byid',
                            cat_id=category.id))


@categories_blueprint.route('/categories/<int:cat_id>/edit', methods=['GET'])
@login_required
def edit_get(cat_id):
    """Render edit form for a category of id cat_id.

    Login required.

    Arguments:
    cat_id (int): the id of the desired category.
    """
    category = c.query(Category).filter_by(id=cat_id).first()

    return render_template('edit_category.html',
                           category=category)


@categories_blueprint.route('/categories/<int:cat_id>/edit', methods=['POST'])
@login_required
def edit_post(cat_id):
    """Edit a category of id cat_id with POST.

    Login required.

    Argument:
    cat_id (int): the id of the desired category.
    """
    category = c.query(Category).filter_by(id=cat_id).first()

    category.name = request.form.get('name')
    category.picture = request.form.get('picture')
    category.description = request.form.get('description')

    c.add(category)
    c.commit()

    flash("The category \"%s\" was successfully edited." % category.name)

    return redirect(url_for('categories.get_byid',
                            cat_id=category.id))


@categories_blueprint.route('/categories/<int:cat_id>/delete', methods=['GET'])
@login_required
def delete_get(cat_id):
    """Render delete form for a category of id cat_id.

    Login required.

    Arguments:
    cat_id (int): the id of the desired category.
    """
    category = c.query(Category).filter_by(id=cat_id).first()

    return render_template('delete_category.html',
                           category=category)


@categories_blueprint.route('/categories/<int:cat_id>/delete', methods=['POST'])  # noqa
@login_required
def delete_post(cat_id):
    """Delete a category of id cat_id with POST.

    Login required.

    Argument:
    cat_id (int): the id of the desired category.
    """
    print cat_id
    category = c.query(Category).filter_by(id=cat_id).first()

    c.delete(category)
    c.commit()

    flash("The category \"%s\" was successfully deleted." % category.name)

    return redirect(url_for('categories.get'))

application/views/client/categories/templates/add_category.html
{% extends "index.html" %}

{% block header %}
<header class="jumbotron">
    <h1 class="display-4">Add a category</h1>
</header>
{% endblock %}

{% block nav %}
<ol class="breadcrumb ml-auto mb-0" style="padding:.5rem 1rem;">
	<li class="breadcrumb-item"><a href="{{ url_for('gifts.get') }}">Gifts</a></li>
	<li class="breadcrumb-item"><a href="{{ url_for('categories.get') }}">Categories</a></li>
    <li class="breadcrumb-item active" aria-current="page">Add</li>
</ol>
{% endblock %}

{% block body %}
<form method='POST' action="{{ url_for('categories.add_post') }}">
    <input name="_csrf_token" type="hidden" value="{{ csrf_token() }}">

	<div class="form-group">
		<label for="name">Name</label>
    	<input id="name" class="form-control" type='text' name='name' placeholder='Name'>
    </div>

    <div class="form-group">
    	<label for="picture">Picture URL</label>
    	<input id="picture" class="form-control" type='text' name='picture' placeholder='Picture URL'>
    </div>

    <div class="form-group">
    	<label for="description">Description</label>
    	<textarea id="description" class="form-control" name='description' placeholder='Description'></textarea>
    </div>

    <button class="btn btn-outline-success" type="submit">Create category</button>
</form>
{% endblock %}

application/views/client/categories/templates/categories.html
{% extends "index.html" %}

{% block header %}
<header class="jumbotron">
    <h1 class="display-4">Categories</h1>
</header>
{% endblock %}

{% block nav %}
<ol class="breadcrumb ml-auto mb-0" style="padding:.5rem 1rem;">
    <li class="breadcrumb-item"><a href="{{ url_for('gifts.get') }}">Gifts</a></li>
    <li class="breadcrumb-item active" aria-current="page">Categories</li>
</ol>
{% endblock %}

{% block body %}
<div class="text-center">
    <a href="{{ url_for('categories.add_get') }}" class="btn btn-success btn-lg">Add a category</a>
<div>
<br>
<div class="list-group">
    {% for category in categories %}
    <a href="{{ url_for('categories.get_byid', cat_id=category.id) }}" class="list-group-item list-group-item-action">{{ category.name }}</a>
    {% endfor %}
</div>
{% endblock %}

application/views/client/categories/templates/category.html
{% extends "index.html" %}

{% block header %}
{% if category.picture %}
<header class="jumbotron" style="background: url('{{ category.picture }}') no-repeat; background-size: cover;">
{% else %}
<header class="jumbotron">
{% endif %}
    <h1 class="display-4">{{ category.name }}</h1>
</header>
{% endblock %}

{% block nav %}
<ol class="breadcrumb ml-auto mb-0" style="padding:.5rem 1rem;">
	<li class="breadcrumb-item"><a href="{{ url_for('gifts.get') }}">Gifts</a></li>
	<li class="breadcrumb-item"><a href="{{ url_for('categories.get') }}">Categories</a></li>
    <li class="breadcrumb-item active" aria-current="page">{{ category.name }}</li>
</ol>
{% endblock %}

{% block body %}

{{ category.description }}<br><br>

<small class="text-muted">
	{% if category.updated_at %}Last updated on {{ category.updated_at.strftime('%d %b %Y at %H:%M') }}<br>{% endif %}
	Created on {{ category.created_at.strftime('%d %b %Y at %H:%M') }}
</small>

<br>
<br>
<a href="{{ url_for('categories.edit_get', cat_id=category.id) }}" class="btn btn-outline-warning">Edit</a>
<a href="{{ url_for('categories.delete_get', cat_id=category.id) }}" class="btn btn-outline-danger">Delete</a>
{% endblock %}

application/views/client/categories/templates/delete_category.html
{% extends "index.html" %}

{% block header %}
{% if category.picture %}
<header class="jumbotron" style="background: url('{{ category.picture }}') no-repeat; background-size: cover;">
{% else %}
<header class="jumbotron">
{% endif %}
    <h1 class="display-4">Delete {{ category.name }}?</h1>
</header>
{% endblock %}

{% block nav %}
<ol class="breadcrumb ml-auto mb-0" style="padding:.5rem 1rem;">
	<li class="breadcrumb-item"><a href="{{ url_for('gifts.get') }}">Gifts</a></li>
	<li class="breadcrumb-item"><a href="{{ url_for('categories.get') }}">Categories</a></li>
    <li class="breadcrumb-item"><a href="{{ url_for('categories.get_byid', cat_id=category.id) }}">{{ category.name }}</a></li>
    <li class="breadcrumb-item active" aria-current="page">Delete</li>
</ol>
{% endblock %}

{% block body %}
<form method="POST" action="{{ url_for('categories.delete_post', cat_id=category.id) }}" class="text-center">
	<input name="_csrf_token" type="hidden" value="{{ csrf_token() }}">

	<button class="btn btn-danger btn-lg" type="submit">Confirm</button>
</form>
{% endblock %}

application/views/client/categories/templates/edit_category.html
{% extends "index.html" %}

{% block header %}
{% if category.picture %}
<header class="jumbotron" style="background: url('{{ category.picture }}') no-repeat; background-size: cover;">
{% else %}
<header class="jumbotron">
{% endif %}
    <h1 class="display-4">Edit {{ category.name }}</h1>
</header>
{% endblock %}

{% block nav %}
<ol class="breadcrumb ml-auto mb-0" style="padding:.5rem 1rem;">
	<li class="breadcrumb-item"><a href="{{ url_for('gifts.get') }}">Gifts</a></li>
	<li class="breadcrumb-item"><a href="{{ url_for('categories.get') }}">Categories</a></li>
    <li class="breadcrumb-item"><a href="{{ url_for('categories.get_byid', cat_id=category.id) }}">{{ category.name }}</a></li>
    <li class="breadcrumb-item active" aria-current="page">Edit</li>
</ol>
{% endblock %}

{% block body %}
<form method="POST" action="{{ url_for('categories.edit_post', cat_id=category.id) }}">
    <input name="_csrf_token" type="hidden" value="{{ csrf_token() }}">

	<div class="form-group">
		<label for="name">Name</label>
    	<input id="name" class="form-control" type='text' name='name' placeholder='Name' value='{{ category.name }}'>
    </div>

    <div class="form-group">
    	<label for="picture">Picture URL</label>
    	<input id="picture" class="form-control" type='text' name='picture' placeholder='Picture URL' value='{{ category.picture }}'>
    </div>

    <div class="form-group">
    	<label for="description">Description</label>
    	<textarea id="description" class="form-control" name='description' placeholder='Description'>{{ category.description }}</textarea>
    </div>

    <button class="btn btn-outline-success" type="submit">Edit</button>
</form>
{% endblock %}